server:
  port: 2000

spring:
  datasource:
    url: 'jdbc:mysql://localhost/first-application'
    username: 'root'
    password: 'root'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2